r"""
Purpose:
Build annual or quarterly event cohort panels and cohort-distribution summaries
from req-specific firm-level panels generated by PanelMaker_FirmLevel.py.

Process:
1. Read the configured year-level or quarter-level firm panel for each event type,
   requirement level, treatment group, and event-pair setting.
2. Build treated and control cohorts within the configured event window.
3. Attach movement event-pair indicators and related other-event timing controls
   when those fields are available.
4. Save cohort CSV files under a variant-specific cohort_data directory.
5. Summarize generated cohort files and write distribution CSVs and figures.

Input:
- `data/roster_variants/<variant>/leader_tier_<tier>/<year|quarter>-level[_A|_B]/ssr_firm_panel_*.csv`
- `InterimData/boardex_ssr_price_sample.csv` (complete firm-product-quarter ATC3 market)
- `data/roster_variants/<variant>/leader_tier_<tier>/event_tables/movement_event_candidates.csv`
- `data/roster_variants/<variant>/leader_tier_<tier>/event_tables/movement_table.csv`
- `data/roster_variants/<variant>/leader_tier_<tier>/event_tables/firm_interlock_panel.csv`

Output:
- `data/roster_variants/<variant>/leader_tier_<tier>/cohort_data/<level-folder>/.../*_<year|quarter>_cohort_*.csv`
- `csv/roster_variants/<variant>/leader_tier_<tier>/.../*.csv`
- `figures/roster_variants/<variant>/leader_tier_<tier>/.../*.png`
"""

from __future__ import annotations

from functools import lru_cache
from pathlib import Path
import re
import matplotlib.pyplot as plt
import pandas as pd

from pipeline_variant_config import (
    OUTPUT_PROJECT_ROOT,
    INTERIM_DATA_PATH,
    PERSONNEL_DEFINITIONS,
    ROSTER_VARIANTS,
    configured_personnel_definitions,
    configured_variants,
    get_variant,
    personnel_output_dir,
)

PROJECT_ROOT = OUTPUT_PROJECT_ROOT
DATA_ROOT = PROJECT_ROOT / "data"
ATC3_PRICE_SAMPLE_PATH = INTERIM_DATA_PATH / "boardex_ssr_price_sample.csv"

MOVEMENT_EVENTS = (
    "to_B_not_in_A",
    "to_B_still_in_A",
    "interlock_dissolution",
)
INDIRECT_INTERLOCK_EVENT = "indirect_interlock"

EVENT_CONFIGS = {
    "to_B_not_in_A": {
        "panel_stem": "ssr_firm_panel_to_B_not_in_A",
        "other_col": "other_event_not",
        "ever_col": "ever_not",
    },
    "to_B_still_in_A": {
        "panel_stem": "ssr_firm_panel_to_B_still_in_A",
        "other_col": "other_event_still",
        "ever_col": "ever_still",
    },
    "interlock_dissolution": {
        "panel_stem": "ssr_firm_panel_interlock_dissolution_leave_B",
        "other_col": "other_event_dissolution",
        "ever_col": "ever_dissolution",
    },
    INDIRECT_INTERLOCK_EVENT: {
        "panel_stem": "ssr_firm_panel_indirect_interlock",
    },
}

CONTROL_FOLDER_MAP = {
    "pure_control": "Pure Control",
    "not_yet": "Not Yet",
    "not": "Not",
}

DISTRIBUTION_CONFIGS = {
    "product": {
        "id_cols": ["BoardName", "product"],
        "ylabel": "Number of BoardName-Product Pairs",
        "figure_root": "cohort_distribution_product",
        "title_label": "product distribution",
    },
    "firm": {
        "id_cols": ["BoardName"],
        "ylabel": "Number of Unique BoardName",
        "figure_root": "cohort_distribution_firm",
        "title_label": "firm distribution",
    },
}


def normalize_firm_key(value: object) -> str:
    """Normalize firm names for event-partner and price-sample matching."""
    if pd.isna(value):
        return ""
    return str(value).strip().upper()


def normalize_product_key(value: object) -> str:
    """Normalize product names for price-sample matching."""
    if pd.isna(value):
        return ""
    return str(value).strip().upper()


@lru_cache(maxsize=1)
def load_atc3_product_panel() -> pd.DataFrame:
    """Load the complete price-sample ATC3 market without roster filtering."""
    required = ["BoardName", "year", "quarter", "product", "atc3"]
    if not ATC3_PRICE_SAMPLE_PATH.exists():
        raise FileNotFoundError(f"Missing ATC3 price sample: {ATC3_PRICE_SAMPLE_PATH}")
    price = pd.read_csv(
        ATC3_PRICE_SAMPLE_PATH,
        usecols=required,
        low_memory=False,
    ).dropna(subset=required)
    price["BoardName"] = price["BoardName"].astype(str).str.strip()
    price["product"] = price["product"].astype(str).str.strip()
    price["atc3"] = price["atc3"].astype(str).str.strip()
    price["year"] = pd.to_numeric(price["year"], errors="raise").astype(int)
    price["quarter"] = pd.to_numeric(price["quarter"], errors="raise").astype(int)
    if not price["quarter"].between(1, 4).all():
        raise ValueError("ATC3 price sample contains invalid quarter values")
    price["_time_id"] = price["year"] * 4 + price["quarter"] - 1
    price["_firm_key"] = price["BoardName"].map(normalize_firm_key)
    price["_product_key"] = price["product"].map(normalize_product_key)
    return price.drop_duplicates(
        subset=["_time_id", "_firm_key", "product", "atc3"]
    ).reset_index(drop=True)


@lru_cache(maxsize=2)
def load_atc3_market_indices(panel_level: str) -> tuple[dict, dict]:
    """Build cached event-period firm/product ATC3 indices."""
    market = load_atc3_product_panel()
    if panel_level == "year":
        # Annual events are anchored at Q1, so annual sharing also uses Q1.
        market = market.loc[market["quarter"].eq(1)].copy()
        market["_panel_time"] = market["year"]
    elif panel_level == "quarter":
        market = market.copy()
        market["_panel_time"] = market["_time_id"]
    else:
        raise ValueError("panel_level must be 'year' or 'quarter'")

    partner_index = (
        market.groupby(["_panel_time", "_firm_key"])["atc3"]
        .agg(lambda values: set(values))
        .to_dict()
    )
    product_index = (
        market.groupby(["_panel_time", "_firm_key", "_product_key"])["atc3"]
        .agg(lambda values: set(values))
        .to_dict()
    )
    return partner_index, product_index


# ========================== USER CONFIG ==========================
RUN_CONFIG = {
    "event_types": [
        "to_B_not_in_A",
        "to_B_still_in_A",
        "interlock_dissolution",
    ],
    "event_requirements": [0, 1, 2],
    "treat_types": ["event"],
    "control_types": ["pure_control", "not_yet", "not"],
    "control_variations": [],
    # Cohort event window: annual t-1 through t+1; quarterly t-4 through t+7.
    "window_pre_years": 1,
    "window_post_years": 1,
    "window_pre_quarters": 4,
    "window_post_quarters": 7,
    "balanced_states": [1],
    # Pipeline3 keeps treated observations and records overlapping events as
    # a control variable instead of excluding the treated event.
    "exclude_treated_window_other_event": False,
    "treatment_groups": ["B", "A"],
    "include_eventpair": [0],
    "plot_start_year": 2009,
    "plot_end_year": 2018,
    "roster_variants": configured_variants(),
    "personnel_definitions": configured_personnel_definitions(),
}
"""
        "to_B_not_in_A",
        "to_B_still_in_A",
        "interlock_dissolution",
        "indirect_interlock",
"""
# ===============================================================


def is_indirect_interlock(event_type: str) -> bool:
    return event_type == INDIRECT_INTERLOCK_EVENT


def build_large_sample_suffix(large_sample: int, personnel_definition: str) -> str:
    """Return movement file suffix for the configured sample definition."""
    if large_sample not in {0, 1}:
        raise ValueError("large_sample must be 0 or 1")
    if large_sample == 0:
        return ""
    if personnel_definition not in PERSONNEL_DEFINITIONS:
        raise ValueError("personnel_definition must be one of: narrow, medium, broad")
    return f"_large_sample_{personnel_definition}"


def should_skip_repeated_nondirectional_run(
    event_type: str,
    treatment_group: str,
    include_eventpair: int,
    canonical_treatment_group: str,
    canonical_include_eventpair: int,
) -> bool:
    if not is_indirect_interlock(event_type):
        return False
    return (
        treatment_group != canonical_treatment_group
        or include_eventpair != canonical_include_eventpair
    )


def get_panel_path(
    roster_variant: str,
    personnel_definition: str,
    event_type: str,
    event_requirement: int,
    treatment_group: str,
) -> Path:
    req_folder = f"req{event_requirement}"
    metadata = get_variant(roster_variant)
    panel_level = str(
        metadata.get("regression_panel_level", metadata["panel_level"])
    )
    variant_root = personnel_output_dir(roster_variant, personnel_definition)
    if is_indirect_interlock(event_type):
        return (
            variant_root
            / f"{panel_level}-level"
            / f"{EVENT_CONFIGS[event_type]['panel_stem']}_{req_folder}.csv"
        )
    return (
        variant_root
        / f"{panel_level}-level_{treatment_group}"
        / f"{EVENT_CONFIGS[event_type]['panel_stem']}_{req_folder}.csv"
    )


def get_level_folder(
    panel_level: str,
    event_type: str,
    treatment_group: str,
    include_eventpair: int,
) -> str:
    if is_indirect_interlock(event_type):
        return f"{panel_level}-level"

    counterpart = "B" if treatment_group == "A" else "A"
    relation = "with" if include_eventpair == 1 else "without"
    return f"{panel_level}-level_{treatment_group}_{relation}_{counterpart}"


def make_time_id(frame: pd.DataFrame, panel_level: str) -> pd.Series:
    """Create an integer time index for annual or quarterly observations."""
    if panel_level == "year":
        return frame["year"].astype(int)
    return frame["year"].astype(int) * 4 + frame["quarter"].astype(int) - 1


def time_label(year: int, quarter: int | None, panel_level: str) -> str:
    """Return the filename and column label for one cohort period."""
    return str(year) if panel_level == "year" else f"{year}q{int(quarter)}"


class CohortPanelMaker:
    """Generate annual or quarterly event cohort CSV files."""

    def __init__(self, config: dict) -> None:
        self.config = config
        self.roster_variant = ""
        self.panel_level = ""
        self.variant_root = Path()
        self.movement_candidates: pd.DataFrame | None = None
        self.atc3_movement_index: dict[tuple, dict] = {}
        self.movement_table: pd.DataFrame | None = None
        self.firm_interlock_panel: pd.DataFrame | None = None
        self.other_event_timing: dict[tuple[str, str, int, str], pd.DataFrame] = {}

    def run(self) -> None:
        for roster_variant in self.config["roster_variants"]:
            for personnel_definition in self.config["personnel_definitions"]:
                self.roster_variant = str(roster_variant)
                self.personnel_definition = str(personnel_definition)
                metadata = get_variant(self.roster_variant)
                self.panel_level = str(
                    metadata.get("regression_panel_level", metadata["panel_level"])
                )
                self.variant_root = personnel_output_dir(
                    self.roster_variant, self.personnel_definition
                )
                self.movement_candidates = None
                self.atc3_movement_index = {}
                self.movement_table = None
                self.firm_interlock_panel = None
                self.other_event_timing = {}
                event_types = self.config["event_types"]
                control_types = self.config["control_types"]
                treatment_groups = self.config["treatment_groups"]
                include_eventpair_values = self.config["include_eventpair"]
                event_requirements = self.config["event_requirements"]
                balanced_states = self.config["balanced_states"]
                canonical_treatment_group = treatment_groups[0]
                canonical_include_eventpair = include_eventpair_values[0]

                for treatment_group in treatment_groups:
                    for include_eventpair in include_eventpair_values:
                        for event_type in event_types:
                            if should_skip_repeated_nondirectional_run(
                                event_type=event_type,
                                treatment_group=treatment_group,
                                include_eventpair=include_eventpair,
                                canonical_treatment_group=canonical_treatment_group,
                                canonical_include_eventpair=canonical_include_eventpair,
                            ):
                                continue
                            for event_requirement in event_requirements:
                                for control_type in control_types:
                                    for balanced in balanced_states:
                                        direction_msg = (
                                            "treatment_group=ignored, include_eventpair=ignored"
                                            if is_indirect_interlock(event_type)
                                            else (
                                                f"treatment_group={treatment_group}, "
                                                f"include_eventpair={include_eventpair}"
                                            )
                                        )
                                        print(
                                            "Running cohort build: "
                                            f"variant={self.roster_variant}, tier={self.personnel_definition}, "
                                            f"level={self.panel_level}, {direction_msg}, "
                                            f"event_type={event_type}, req{event_requirement}, "
                                            f"control_type={control_type}, balanced={balanced}"
                                        )
                                        self.build_configuration(
                                            event_type=event_type,
                                            event_requirement=event_requirement,
                                            control_type=control_type,
                                            balanced=balanced,
                                            treatment_group=treatment_group,
                                            include_eventpair=include_eventpair,
                                        )

    def build_configuration(
        self,
        event_type: str,
        event_requirement: int,
        control_type: str,
        balanced: int,
        treatment_group: str,
        include_eventpair: int,
    ) -> None:
        req_folder = f"req{event_requirement}"
        panel_path = get_panel_path(
            roster_variant=self.roster_variant,
            personnel_definition=self.personnel_definition,
            event_type=event_type,
            event_requirement=event_requirement,
            treatment_group=treatment_group,
        )

        df = pd.read_csv(panel_path)
        df["year"] = pd.to_numeric(df["year"], errors="raise").astype(int)
        if self.panel_level == "quarter":
            df["quarter"] = pd.to_numeric(df["quarter"], errors="raise").astype(int)
        df["_time_id"] = make_time_id(df, self.panel_level)
        df["event"] = pd.to_numeric(df["event"], errors="raise").astype("int8")
        df["pure_event"] = pd.to_numeric(df["pure_event"], errors="raise").astype("int8")
        df["first_event_year"] = pd.to_numeric(df["first_event_year"], errors="coerce")
        if "first_event_period" in df.columns:
            df["first_event_period"] = pd.to_numeric(df["first_event_period"], errors="coerce")
        if self.panel_level == "quarter" and "first_event_quarter" in df.columns:
            df["first_event_quarter"] = pd.to_numeric(df["first_event_quarter"], errors="coerce")

        level_folder = get_level_folder(
            panel_level=self.panel_level,
            event_type=event_type,
            treatment_group=treatment_group,
            include_eventpair=include_eventpair,
        )
        output_root = self.variant_root / "cohort_data" / level_folder / "event" / req_folder

        start_year = int(self.config["plot_start_year"])
        end_year = int(self.config["plot_end_year"])

        if self.panel_level == "year":
            cohort_periods = [(year, None) for year in range(start_year, end_year + 1)]
        else:
            cohort_periods = [
                (year, quarter)
                for year in range(start_year, end_year + 1)
                for quarter in range(1, 5)
            ]

        for cohort_year, cohort_quarter in cohort_periods:
            cohort_label = time_label(cohort_year, cohort_quarter, self.panel_level)
            event_col = f"event_{cohort_label}"
            balance_col = f"balance_panel_{cohort_label}"
            if event_col not in df.columns or balance_col not in df.columns:
                continue
            df[event_col] = pd.to_numeric(df[event_col], errors="raise").astype("int8")
            df[balance_col] = pd.to_numeric(df[balance_col], errors="raise").astype("int8")

            cohort_df = self.build_one_cohort(
                df=df,
                event_type=event_type,
                event_requirement=event_requirement,
                control_type=control_type,
                balanced=balanced,
                treatment_group=treatment_group,
                include_eventpair=include_eventpair,
                cohort_year=cohort_year,
                cohort_quarter=cohort_quarter,
            )

            output_dir = output_root / CONTROL_FOLDER_MAP[control_type]
            output_dir.mkdir(parents=True, exist_ok=True)
            balanced_suffix = "_balanced" if balanced == 1 else ""
            output_file = (
                output_dir
                / f"{event_type}_{self.panel_level}_cohort_{cohort_label}{balanced_suffix}.csv"
            )
            cohort_df.to_csv(output_file, index=False)

        print(f"Finished. Files saved to: {output_root}")

    def build_one_cohort(
        self,
        df: pd.DataFrame,
        event_type: str,
        event_requirement: int,
        control_type: str,
        balanced: int,
        treatment_group: str,
        include_eventpair: int,
        cohort_year: int,
        cohort_quarter: int | None,
    ) -> pd.DataFrame:
        id_cols = ["BoardName", "product"]
        cohort_label = time_label(cohort_year, cohort_quarter, self.panel_level)
        event_col = f"event_{cohort_label}"
        balance_col = f"balance_panel_{cohort_label}"
        if self.panel_level == "year":
            cohort_time = cohort_year
            pre_periods = int(self.config["window_pre_years"])
            post_periods = int(self.config["window_post_years"])
        else:
            cohort_time = cohort_year * 4 + int(cohort_quarter) - 1
            pre_periods = int(
                self.config.get("window_pre_quarters", self.config["window_pre_years"] * 4)
            )
            post_periods = int(
                self.config.get("window_post_quarters", self.config["window_post_years"] * 4)
            )
        window_periods = list(range(cohort_time - pre_periods, cohort_time + post_periods + 1))
        expected_n = len(window_periods)
        df_window = df[df["_time_id"].isin(window_periods)].copy()

        pure_event_at_t = (
            df.loc[df["_time_id"].eq(cohort_time)]
            .groupby("BoardName")["pure_event"]
            .max()
        )
        treated_candidate_firms = set(pure_event_at_t[pure_event_at_t.eq(1)].index)
        control_candidate_firms = set(df["BoardName"].dropna().unique()) - treated_candidate_firms
        req_event_firms = set(df.loc[df[event_col].eq(1), "BoardName"].dropna().unique())
        final_treated_firms = treated_candidate_firms & req_event_firms

        # Window-overlapping events are modeled separately and do not disqualify treated firms.

        treated = df_window[df_window["BoardName"].isin(final_treated_firms)].copy()
        if balanced == 1:
            treated_obs = treated.groupby(id_cols).size()
            complete_treated = treated_obs[treated_obs.eq(expected_n)].index
            treated = treated[
                treated.set_index(id_cols).index.isin(complete_treated)
                & treated[balance_col].eq(1)
            ].copy()

        no_pure_event = df_window.groupby(id_cols)["pure_event"].max()
        valid_control_units = no_pure_event[no_pure_event.eq(0)].index
        controls = df_window[
            df_window["BoardName"].isin(control_candidate_firms)
            & df_window.set_index(id_cols).index.isin(valid_control_units)
        ].copy()

        controls_obs = controls.groupby(id_cols).size()
        complete_controls = controls_obs[controls_obs.eq(expected_n)].index
        controls = controls[
            controls.set_index(id_cols).index.isin(complete_controls)
        ].copy()

        # Apply control eligibility at the firm level, not row by row.  A firm
        # that has an event in any period must not re-enter the control group
        # through its pre-event or post-event rows.
        first_event_by_firm = controls.groupby("BoardName")["first_event_period"].min()
        if control_type == "pure_control":
            eligible_firms = set(first_event_by_firm[first_event_by_firm.isna()].index)
            controls = controls[controls["BoardName"].isin(eligible_firms)].copy()
        elif control_type == "not_yet":
            end_time = cohort_time + post_periods
            eligible_firms = set(
                first_event_by_firm[
                    first_event_by_firm.isna() | (first_event_by_firm > end_time)
                ].index
            )
            controls = controls[controls["BoardName"].isin(eligible_firms)].copy()

        if include_eventpair == 0 and not controls.empty and not is_indirect_interlock(event_type):
            controls = self.filter_counterpart_only_controls(
                controls=controls,
                event_type=event_type,
                event_requirement=event_requirement,
                treatment_group=treatment_group,
                cohort_time=cohort_time,
            )

        if not controls.empty and controls[event_col].ne(0).any():
            group_label = "non-directional" if is_indirect_interlock(event_type) else treatment_group
            raise AssertionError(
                f"Controls should have {event_col}=0 after pure_event filtering: "
                f"{event_type}, req{event_requirement}, {group_label}, {cohort_label}"
            )

        cohort_df = pd.concat([treated, controls], axis=0, ignore_index=True)
        sort_time = ["year"] if self.panel_level == "year" else ["year", "quarter"]
        cohort_df = cohort_df.sort_values(id_cols + sort_time).reset_index(drop=True)

        # Add a firm-level indicator for any other qualifying event during the
        # cohort window. The focal event at t is excluded, while same-type
        # events at other dates and all other event types are included.
        cohort_df = self.add_window_other_event_marker(
            cohort_df=cohort_df,
            event_type=event_type,
            event_requirement=event_requirement,
            treatment_group=treatment_group,
            cohort_time=cohort_time,
            window_periods=window_periods,
        )
        if self.config.get("exclude_treated_window_other_event", False):
            cohort_df = cohort_df.loc[
                ~(
                    cohort_df[event_col].eq(1)
                    & cohort_df["window_other_event"].eq(1)
                )
            ].copy()

        # Build ATC3 sharing at the cohort stage. For a treated FirmA row,
        # compare its product ATC3 with every product sold by the event's
        # FirmB partner at the event period. For a treated FirmB row, reverse
        # the direction. The indicator is frozen at the event-period product
        # comparison and copied across the complete event window.
        cohort_df = self.add_atc3_sharing(
            cohort_df=cohort_df,
            event_type=event_type,
            event_requirement=event_requirement,
            treatment_group=treatment_group,
            cohort_time=cohort_time,
            event_col=event_col,
        )

        if not is_indirect_interlock(event_type):
            cohort_df = self.add_other_event_markers(
                cohort_df=cohort_df,
                event_type=event_type,
                event_requirement=event_requirement,
                treatment_group=treatment_group,
                cohort_time=cohort_time,
            )
            cohort_df = self.add_ever_event_markers(
                cohort_df=cohort_df,
                cohort_time=cohort_time,
                event_requirement=event_requirement,
                treatment_group=treatment_group,
            )
        return cohort_df

    def add_window_other_event_marker(
        self,
        cohort_df: pd.DataFrame,
        event_type: str,
        event_requirement: int,
        treatment_group: str,
        cohort_time: int,
        window_periods: list[int],
    ) -> pd.DataFrame:
        """Flag firms with any non-focal qualifying event in the cohort window."""
        req_folder = f"req{event_requirement}"
        event_frames: list[pd.DataFrame] = []

        current_events = cohort_df.loc[
            cohort_df["event"].eq(1), ["BoardName", "_time_id"]
        ].drop_duplicates()
        current_events = current_events.assign(event_type=event_type)
        event_frames.append(current_events)

        for other_event in MOVEMENT_EVENTS:
            if other_event == event_type:
                continue
            panel_path = (
                self.variant_root
                / f"{self.panel_level}-level_{treatment_group}"
                / f"{EVENT_CONFIGS[other_event]['panel_stem']}_{req_folder}.csv"
            )
            timing = pd.read_csv(panel_path)
            timing["_time_id"] = make_time_id(timing, self.panel_level)
            timing["event"] = pd.to_numeric(timing["event"], errors="raise").astype("int8")
            timing = timing.loc[
                timing["event"].eq(1), ["BoardName", "_time_id"]
            ].drop_duplicates()
            timing = timing.assign(event_type=other_event)
            event_frames.append(timing)

        all_events = pd.concat(event_frames, ignore_index=True).drop_duplicates()
        all_events = all_events[all_events["_time_id"].isin(window_periods)].copy()
        is_focal_event = (
            all_events["event_type"].eq(event_type)
            & all_events["_time_id"].eq(cohort_time)
        )
        other_event_firms = set(all_events.loc[~is_focal_event, "BoardName"])

        result = cohort_df.copy()
        result["window_other_event"] = (
            result["BoardName"].isin(other_event_firms).astype("int8")
        )
        return result

    def add_atc3_sharing(
        self,
        cohort_df: pd.DataFrame,
        event_type: str,
        event_requirement: int,
        treatment_group: str,
        cohort_time: int,
        event_col: str,
    ) -> pd.DataFrame:
        """Attach event-period product ATC3 overlap for treated firms."""
        result = cohort_df.copy()
        result["atc3_sharing"] = pd.Series(
            0, index=result.index, dtype="int8"
        )
        if is_indirect_interlock(event_type) or result.empty:
            return result

        if self.movement_candidates is None:
            path = self.variant_root / "event_tables" / "movement_event_candidates.csv"
            self.movement_candidates = pd.read_csv(path, low_memory=False)

        treated_firms = set(
            result.loc[
                result["_time_id"].eq(cohort_time)
                & result[event_col].eq(1),
                "BoardName",
            ].dropna()
        )
        treated_keys = {normalize_firm_key(value) for value in treated_firms}
        if not treated_keys:
            return result

        partner_lookup = self.get_atc3_partner_index(
            event_type=event_type,
            event_requirement=event_requirement,
            treatment_group=treatment_group,
        )
        partner_atc3, product_atc3 = load_atc3_market_indices(self.panel_level)

        result["_cohort_firm_key"] = result["BoardName"].map(normalize_firm_key)
        result["_product_key"] = result["product"].map(normalize_product_key)
        event_products = result.loc[
            result["_time_id"].eq(cohort_time)
            & result[event_col].eq(1)
            & result["_cohort_firm_key"].isin(treated_keys),
            ["_cohort_firm_key", "_product_key"],
        ].dropna(subset=["_cohort_firm_key", "_product_key"]).drop_duplicates()

        sharing_pairs: set[tuple[str, str]] = set()
        for treated_key, product_key in event_products.itertuples(index=False, name=None):
            treated_atc_values = product_atc3.get(
                (cohort_time, treated_key, product_key), set()
            )
            partner_atc_values: set[str] = set()
            for partner_key in partner_lookup.get((cohort_time, treated_key), set()):
                partner_atc_values.update(
                    partner_atc3.get((cohort_time, partner_key), set())
                )
            if treated_atc_values.intersection(partner_atc_values):
                sharing_pairs.add((treated_key, product_key))

        if sharing_pairs:
            row_index = pd.MultiIndex.from_frame(
                result[["_cohort_firm_key", "_product_key"]]
            )
            sharing_index = pd.MultiIndex.from_tuples(
                sharing_pairs, names=["_cohort_firm_key", "_product_key"]
            )
            result.loc[row_index.isin(sharing_index), "atc3_sharing"] = 1

        # Controls are never assigned the treated-side sharing label.
        result.loc[~result[event_col].eq(1), "atc3_sharing"] = 0
        return result.drop(columns=["_cohort_firm_key", "_product_key"])

    def get_atc3_partner_index(
        self,
        event_type: str,
        event_requirement: int,
        treatment_group: str,
    ) -> dict[tuple[int, str], set[str]]:
        """Return a cached event-time treated-firm to partner-firm index."""
        cache_key = (
            event_type,
            int(event_requirement),
            str(treatment_group).upper(),
            self.panel_level,
        )
        if cache_key in self.atc3_movement_index:
            return self.atc3_movement_index[cache_key]
        if self.movement_candidates is None:
            path = self.variant_root / "event_tables" / "movement_event_candidates.csv"
            self.movement_candidates = pd.read_csv(path, low_memory=False)

        movement = self.movement_candidates.copy()
        stay_cols = [
            str(column)
            for column in movement.columns
            if re.fullmatch(r"stay_\d+_years", str(column))
        ]
        if len(stay_cols) != 1:
            raise ValueError(f"Expected exactly one stay_x_years column, found: {stay_cols}")
        stay_col = stay_cols[0]
        movement["year"] = pd.to_numeric(movement["year"], errors="raise").astype(int)
        source_level = str(get_variant(self.roster_variant)["panel_level"])
        if self.panel_level == "quarter":
            if source_level == "year":
                # Annual source events are anchored at Q1 in the regression
                # panel. Raw annual time ids are calendar years, not q_time ids.
                movement["_time_id_A"] = (
                    pd.to_numeric(movement["FirmA_event_time_id"], errors="raise") * 4
                ).astype(int)
                movement["_time_id_B"] = (
                    pd.to_numeric(movement["FirmB_event_time_id"], errors="raise") * 4
                ).astype(int)
            else:
                movement["_time_id_A"] = pd.to_numeric(
                    movement["FirmA_event_time_id"], errors="raise"
                ).astype(int)
                movement["_time_id_B"] = pd.to_numeric(
                    movement["FirmB_event_time_id"], errors="raise"
                ).astype(int)
        else:
            movement["_time_id_A"] = pd.to_numeric(
                movement["FirmA_event_time_id"], errors="raise"
            ).astype(int)
            movement["_time_id_B"] = pd.to_numeric(
                movement["FirmB_event_time_id"], errors="raise"
            ).astype(int)
        movement[stay_col] = pd.to_numeric(movement[stay_col], errors="raise").astype("int8")
        movement["requirement1_A"] = pd.to_numeric(
            movement["requirement1_A"], errors="raise"
        ).astype("int8")
        movement["requirement1_B"] = pd.to_numeric(
            movement["requirement1_B"], errors="raise"
        ).astype("int8")

        valid = movement["event_type"].eq(event_type)
        if event_requirement in {1, 2} and event_type != "interlock_dissolution":
            valid &= movement[stay_col].eq(1)
        if event_requirement == 2:
            requirement_column = (
                "requirement1_A" if str(treatment_group).upper() == "A" else "requirement1_B"
            )
            valid &= movement[requirement_column].eq(1)

        treated_col = "FirmA" if str(treatment_group).upper() == "A" else "FirmB"
        partner_col = "FirmB" if str(treatment_group).upper() == "A" else "FirmA"
        treated_time_col = (
            "_time_id_A" if str(treatment_group).upper() == "A" else "_time_id_B"
        )
        current = movement.loc[
            valid,
            [treated_time_col, treated_col, partner_col],
        ].dropna().copy()
        current = current.rename(columns={treated_time_col: "_treated_time_id"})
        current["_treated_key"] = current[treated_col].map(normalize_firm_key)
        current["_partner_key"] = current[partner_col].map(normalize_firm_key)
        index = (
            current.groupby(["_treated_time_id", "_treated_key"])["_partner_key"]
            .agg(lambda values: set(values))
            .to_dict()
        )
        self.atc3_movement_index[cache_key] = index
        return index

    def filter_counterpart_only_controls(
        self,
        controls: pd.DataFrame,
        event_type: str,
        event_requirement: int,
        treatment_group: str,
        cohort_time: int,
    ) -> pd.DataFrame:
        if self.movement_candidates is None:
            path = self.variant_root / "event_tables" / "movement_event_candidates.csv"
            self.movement_candidates = pd.read_csv(path)

        movement = self.movement_candidates.copy()
        stay_cols = [
            str(column)
            for column in movement.columns
            if re.fullmatch(r"stay_\d+_years", str(column))
        ]
        if len(stay_cols) != 1:
            raise ValueError(f"Expected exactly one stay_x_years column, found: {stay_cols}")

        stay_col = stay_cols[0]
        movement["year"] = pd.to_numeric(movement["year"], errors="raise").astype(int)
        source_level = str(get_variant(self.roster_variant)["panel_level"])
        if self.panel_level == "quarter":
            if source_level == "year":
                movement["_time_id_A"] = (
                    pd.to_numeric(movement["FirmA_event_time_id"], errors="raise") * 4
                ).astype(int)
                movement["_time_id_B"] = (
                    pd.to_numeric(movement["FirmB_event_time_id"], errors="raise") * 4
                ).astype(int)
            else:
                movement["_time_id_A"] = pd.to_numeric(
                    movement["FirmA_event_time_id"], errors="raise"
                ).astype(int)
                movement["_time_id_B"] = pd.to_numeric(
                    movement["FirmB_event_time_id"], errors="raise"
                ).astype(int)
        else:
            movement["_time_id_A"] = pd.to_numeric(
                movement["FirmA_event_time_id"], errors="raise"
            ).astype(int)
            movement["_time_id_B"] = pd.to_numeric(
                movement["FirmB_event_time_id"], errors="raise"
            ).astype(int)
        for col in (stay_col, "requirement1"):
            if col == "requirement1":
                continue
            movement[col] = pd.to_numeric(movement[col], errors="raise").astype("int8")
        movement["requirement1_A"] = pd.to_numeric(
            movement["requirement1_A"], errors="raise"
        ).astype("int8")
        movement["requirement1_B"] = pd.to_numeric(
            movement["requirement1_B"], errors="raise"
        ).astype("int8")

        treated_time_col = (
            "_time_id_A" if str(treatment_group).upper() == "A" else "_time_id_B"
        )
        requirement_column = (
            "requirement1_A" if str(treatment_group).upper() == "A" else "requirement1_B"
        )
        current = movement.loc[
            movement["event_type"].eq(event_type)
            & movement[treated_time_col].eq(cohort_time)
        ].copy()
        if event_requirement in {1, 2}:
            current = current[current[stay_col].eq(1)].copy()
        if event_requirement == 2:
            current = current[current[requirement_column].eq(1)].copy()

        firms_a = set(current["FirmA"].dropna())
        firms_b = set(current["FirmB"].dropna())
        drop_firms = firms_b - firms_a if treatment_group == "A" else firms_a - firms_b
        return controls[~controls["BoardName"].isin(drop_firms)].copy()

    def add_other_event_markers(
        self,
        cohort_df: pd.DataFrame,
        event_type: str,
        event_requirement: int,
        treatment_group: str,
        cohort_time: int,
    ) -> pd.DataFrame:
        if event_type == "to_B_not_in_A":
            other_events = ["to_B_still_in_A", "interlock_dissolution"]
        elif event_type == "to_B_still_in_A":
            other_events = ["to_B_not_in_A", "interlock_dissolution"]
        else:
            other_events = ["to_B_not_in_A", "to_B_still_in_A"]

        cohort_df = cohort_df.copy()
        req_folder = f"req{event_requirement}"

        for other_event in other_events:
            cache_key = (other_event, treatment_group, event_requirement, self.roster_variant)
            if cache_key not in self.other_event_timing:
                panel_path = (
                    self.variant_root
                    / f"{self.panel_level}-level_{treatment_group}"
                    / f"{EVENT_CONFIGS[other_event]['panel_stem']}_{req_folder}.csv"
                )
                timing = pd.read_csv(panel_path)
                timing["_time_id"] = make_time_id(timing, self.panel_level)
                timing["year"] = pd.to_numeric(timing["year"], errors="raise").astype(int)
                timing["event"] = pd.to_numeric(timing["event"], errors="raise").astype("int8")
                self.other_event_timing[cache_key] = (
                    timing.loc[timing["event"].eq(1), ["BoardName", "_time_id"]]
                    .drop_duplicates()
                    .reset_index(drop=True)
                )

            timing_index = pd.MultiIndex.from_frame(
                self.other_event_timing[cache_key][["BoardName", "_time_id"]]
            )
            row_index = pd.MultiIndex.from_frame(cohort_df[["BoardName", "_time_id"]])
            cohort_df[EVENT_CONFIGS[other_event]["other_col"]] = (
                row_index.isin(timing_index)
            ).astype("int8")

        return cohort_df

    def add_ever_event_markers(
        self,
        cohort_df: pd.DataFrame,
        cohort_time: int,
        event_requirement: int,
        treatment_group: str,
    ) -> pd.DataFrame:
        if self.movement_table is None:
            path = self.variant_root / "event_tables" / "movement_table.csv"
            self.movement_table = pd.read_csv(path)
            self.movement_table["year"] = pd.to_numeric(
                self.movement_table["year"],
                errors="raise",
            ).astype(int)
            if self.panel_level == "quarter" and "quarter" not in self.movement_table.columns:
                self.movement_table["quarter"] = 1
            self.movement_table["_time_id"] = make_time_id(
                self.movement_table, self.panel_level
            )
            self.movement_table["firm_type"] = self.movement_table["firm_type"].astype(str).str.upper()
            for req_col in ("req0", "req1", "req2"):
                self.movement_table[req_col] = pd.to_numeric(
                    self.movement_table[req_col],
                    errors="raise",
                ).astype("int8")

        req_col = f"req{event_requirement}"
        prior_events = self.movement_table.loc[
            self.movement_table["firm_type"].eq(treatment_group)
            & self.movement_table[req_col].eq(1)
            & self.movement_table["_time_id"].lt(cohort_time)
        ]

        cohort_df = cohort_df.copy()
        for prior_event in MOVEMENT_EVENTS:
            firms = set(prior_events.loc[prior_events["event_type"].eq(prior_event), "BoardName"])
            cohort_df[EVENT_CONFIGS[prior_event]["ever_col"]] = (
                cohort_df["BoardName"].isin(firms).astype("int8")
            )
        return cohort_df

class CohortPlotter:
    """Plot treated/control cohort distributions from generated cohort CSV files."""

    def __init__(self, config: dict) -> None:
        self.config = config
        self.roster_variant = ""
        self.personnel_definition = ""
        self.panel_level = ""
        self.variant_root = Path()

    def run(self) -> None:
        for roster_variant in self.config["roster_variants"]:
            for personnel_definition in self.config["personnel_definitions"]:
                self.roster_variant = str(roster_variant)
                self.personnel_definition = str(personnel_definition)
                metadata = get_variant(self.roster_variant)
                self.panel_level = str(
                    metadata.get("regression_panel_level", metadata["panel_level"])
                )
                self.variant_root = personnel_output_dir(
                    self.roster_variant, self.personnel_definition
                )
                event_types = self.config["event_types"]
                treat_types = self.config["treat_types"]
                control_types = self.config["control_types"]
                control_variations = self.config["control_variations"]
                treatment_groups = self.config["treatment_groups"]
                include_eventpair_values = self.config["include_eventpair"]
                event_requirements = self.config["event_requirements"]
                balanced_states = self.config["balanced_states"]
                canonical_treatment_group = treatment_groups[0]
                canonical_include_eventpair = include_eventpair_values[0]

                for treatment_group in treatment_groups:
                    for include_eventpair in include_eventpair_values:
                        for event_type in event_types:
                            if should_skip_repeated_nondirectional_run(
                                event_type=event_type,
                                treatment_group=treatment_group,
                                include_eventpair=include_eventpair,
                                canonical_treatment_group=canonical_treatment_group,
                                canonical_include_eventpair=canonical_include_eventpair,
                            ):
                                continue
                            for event_requirement in event_requirements:
                                for unit_level in DISTRIBUTION_CONFIGS:
                                    self.plot_configuration(
                                        event_type=event_type,
                                        event_requirement=event_requirement,
                                        treatment_group=treatment_group,
                                        include_eventpair=include_eventpair,
                                        unit_level=unit_level,
                                        treat_types=treat_types,
                                        control_types=control_types,
                                        control_variations=control_variations,
                                        balanced_states=balanced_states,
                                    )

    def plot_configuration(
        self,
        event_type: str,
        event_requirement: int,
        treatment_group: str,
        include_eventpair: int,
        unit_level: str,
        treat_types: list[str],
        control_types: list[str],
        control_variations: list[str],
        balanced_states: list[int],
    ) -> None:
        unit_config = DISTRIBUTION_CONFIGS[unit_level]
        id_cols = unit_config["id_cols"]
        start_year = int(self.config["plot_start_year"])
        end_year = int(self.config["plot_end_year"])
        if self.panel_level == "year":
            periods = [(year, None) for year in range(start_year, end_year + 1)]
        else:
            periods = [
                (year, quarter)
                for year in range(start_year, end_year + 1)
                for quarter in range(1, 5)
            ]
        labels = [time_label(year, quarter, self.panel_level) for year, quarter in periods]
        level_folder = get_level_folder(
            panel_level=self.panel_level,
            event_type=event_type,
            treatment_group=treatment_group,
            include_eventpair=include_eventpair,
        )
        level_label = get_level_folder(
            panel_level=self.panel_level,
            event_type=event_type,
            treatment_group=treatment_group,
            include_eventpair=include_eventpair,
        )
        req_folder = f"req{event_requirement}"

        for treat_type in treat_types:
            cohort_root = self.variant_root / "cohort_data" / level_folder / treat_type / req_folder
            for control_type in control_types:
                folder_name = CONTROL_FOLDER_MAP[control_type]
                for balanced in balanced_states:
                    balanced_label = "balanced" if balanced == 1 else "unbalanced"
                    balanced_suffix = "_balanced" if balanced == 1 else ""
                    treated_counts: list[int] = []

                    control_counts: list[int] = []
                    if event_requirement in {0, 1, 2}:
                        for label in labels:
                            event_col = f"event_{label}"
                            file_path = (
                                cohort_root
                                / folder_name
                                / f"{event_type}_{self.panel_level}_cohort_{label}{balanced_suffix}.csv"
                            )
                            if not file_path.exists():
                                treated_counts.append(0)
                                control_counts.append(0)
                                continue

                            df = pd.read_csv(file_path)
                            treated = df[df[event_col].eq(1)]
                            controls = df[df[event_col].eq(0)]
                            treated_counts.append(treated[id_cols].drop_duplicates().shape[0])
                            control_counts.append(controls[id_cols].drop_duplicates().shape[0])

                        self.draw_two_bar_plot(
                            years=labels,
                            treated_counts=treated_counts,
                            control_counts=control_counts,
                            unit_config=unit_config,
                            title=(
                                f"{level_folder} | {unit_config['title_label']} | "
                                f"{event_type} | {treat_type} | req{event_requirement} | "
                                f"{control_type} | {balanced_label}"
                            ),
                            out_path=(
                                PROJECT_ROOT
                                / "figures"
                                / "roster_variants"
                                / self.roster_variant
                                / f"leader_tier_{self.personnel_definition}"
                                / unit_config["figure_root"]
                                / level_folder
                                / treat_type
                                / req_folder
                                / folder_name
                                / f"{event_type}_{level_label}_{treat_type}_{control_type}_{balanced_label}.png"
                            ),
                        )
                        csv_dir = (
                            PROJECT_ROOT
                            / "csv"
                            / "roster_variants"
                            / self.roster_variant
                            / f"leader_tier_{self.personnel_definition}"
                            / unit_config["figure_root"]
                            / level_folder
                            / treat_type
                            / req_folder
                            / folder_name
                        )
                        csv_dir.mkdir(parents=True, exist_ok=True)
                        pd.DataFrame(
                            {"Period": labels, "Treated": treated_counts, "Control": control_counts}
                        ).to_csv(
                            csv_dir
                            / f"{event_type}_{level_label}_{treat_type}_{control_type}_{balanced_label}.csv",
                            index=False,
                        )

        print(
            "Figures and CSV tables generated and saved to:\n"
            f"  {PROJECT_ROOT}/figures/roster_variants/{self.roster_variant}/"
            f"leader_tier_{self.personnel_definition}/{unit_config['figure_root']}/\n"
            f"  {PROJECT_ROOT}/csv/roster_variants/{self.roster_variant}/"
            f"leader_tier_{self.personnel_definition}/{unit_config['figure_root']}/"
        )

    def draw_two_bar_plot(
        self,
        years: list[int],
        treated_counts: list[int],
        control_counts: list[int],
        unit_config: dict,
        title: str,
        out_path: Path,
    ) -> None:
        x = list(range(len(years)))
        width = 0.35
        plt.figure(figsize=(14, 6))
        bars_treated = plt.bar(
            [index - width / 2 for index in x],
            treated_counts,
            width=width,
            label="Treated",
        )
        bars_control = plt.bar(
            [index + width / 2 for index in x],
            control_counts,
            width=width,
            label="Control",
        )
        self.finish_plot(
            years=years,
            bars_to_label=[bars_treated, bars_control],
            extra_totals=None,
            unit_config=unit_config,
            title=title,
            out_path=out_path,
        )

    def finish_plot(
        self,
        years: list[int],
        bars_to_label: list,
        extra_totals: list[int] | None,
        unit_config: dict,
        title: str,
        out_path: Path,
    ) -> None:
        for bars in bars_to_label:
            for bar in bars:
                height = bar.get_height()
                plt.text(
                    bar.get_x() + bar.get_width() / 2,
                    height + 1,
                    f"{int(height)}",
                    ha="center",
                    va="bottom",
                    fontsize=10,
                )

        if extra_totals is not None:
            x = list(range(len(years)))
            for xpos, total in zip([index + 0.35 / 2 for index in x], extra_totals):
                plt.text(
                    xpos,
                    total + 1,
                    f"{int(total)}",
                    ha="center",
                    va="bottom",
                    fontsize=10,
                )

        plt.xticks(list(range(len(years))), years, rotation=45)
        plt.ylabel(unit_config["ylabel"])
        plt.title(title)
        plt.legend()
        plt.tight_layout()
        out_path.parent.mkdir(parents=True, exist_ok=True)
        plt.savefig(out_path)
        plt.close()


if __name__ == "__main__":
    CohortPanelMaker(RUN_CONFIG).run()
    CohortPlotter(RUN_CONFIG).run()
