r"""
Purpose:
Build quarter-level event cohort panels from the req-specific
firm-level panels generated by PanelMaker_FirmLevel.py.

The script handles movement event-style cohorts:
- to_B_not_in_A
- to_B_still_in_A
- interlock_dissolution
and non-directional indirect interlock cohorts:
- indirect_interlock

It does not generate first-event or year-level cohorts.
"""

from __future__ import annotations

from pathlib import Path
import re

import matplotlib.pyplot as plt
import pandas as pd

PROJECT_ROOT = Path(__file__).resolve().parents[2]
DATA_ROOT = PROJECT_ROOT / "data"
EVENT_TABLES_PATH = DATA_ROOT / "event_tables"
COHORT_DATA_ROOT = DATA_ROOT / "cohort_data"

MOVEMENT_CANDIDATES_PATH = EVENT_TABLES_PATH / "movement_event_candidates.csv"
MOVEMENT_TABLE_PATH = EVENT_TABLES_PATH / "movement_table.csv"
FIRM_INTERLOCK_PANEL_PATH = EVENT_TABLES_PATH / "firm_interlock_panel.csv"

MOVEMENT_EVENTS = (
    "to_B_not_in_A",
    "to_B_still_in_A",
    "interlock_dissolution",
)
INDIRECT_INTERLOCK_EVENT = "indirect_interlock"

EVENT_CONFIGS = {
    "to_B_not_in_A": {
        "panel_stem": "ssr_firm_panel_to_B_not_in_A",
        "other_col": "other_event_not",
        "ever_col": "ever_not",
    },
    "to_B_still_in_A": {
        "panel_stem": "ssr_firm_panel_to_B_still_in_A",
        "other_col": "other_event_still",
        "ever_col": "ever_still",
    },
    "interlock_dissolution": {
        "panel_stem": "ssr_firm_panel_interlock_dissolution_leave_B",
        "other_col": "other_event_dissolution",
        "ever_col": "ever_dissolution",
    },
    INDIRECT_INTERLOCK_EVENT: {
        "panel_stem": "ssr_firm_panel_indirect_interlock",
    },
}

CONTROL_FOLDER_MAP = {
    "pure_control": "Pure Control",
    "not_yet": "Not Yet",
    "not": "Not",
}

REQ2_STACK_SEGMENTS = (
    "changing",
    "stable_interlock",
    "stable_no_interlock",
)

REQ2_STACK_COLORS = {
    "changing": "#C65D4A",
    "stable_interlock": "#4B8F8C",
    "stable_no_interlock": "#C7B299",
}

DISTRIBUTION_CONFIGS = {
    "product": {
        "id_cols": ["BoardName", "product"],
        "ylabel": "Number of BoardName-Product Pairs",
        "figure_root": "cohort_distribution_product",
        "title_label": "product distribution",
    },
    "firm": {
        "id_cols": ["BoardName"],
        "ylabel": "Number of Unique BoardName",
        "figure_root": "cohort_distribution_firm",
        "title_label": "firm distribution",
    },
}


# ========================== USER CONFIG ==========================
RUN_CONFIG = {
    "event_types": [
        "indirect_interlock",
    ],
    "event_requirements": [0, 1, 2],
    "treat_types": ["event"],
    "control_types": ["pure_control", "not_yet", "not"],
    "control_variations": ["stable", "changing", "stable_interlock", "stable_no_interlock"],
    "window_pre": 1,
    "window_post": 1,
    "balanced_states": [1],
    "treatment_groups": ["B", "A"],
    "include_eventpair": [0],
    "plot_start_year": 2009,
    "plot_end_year": 2018,
}
"""
        "to_B_not_in_A",
        "to_B_still_in_A",
        "interlock_dissolution",
"""
# ===============================================================


def is_indirect_interlock(event_type: str) -> bool:
    return event_type == INDIRECT_INTERLOCK_EVENT


def should_skip_repeated_nondirectional_run(
    event_type: str,
    treatment_group: str,
    include_eventpair: int,
    canonical_treatment_group: str,
    canonical_include_eventpair: int,
) -> bool:
    if not is_indirect_interlock(event_type):
        return False
    return (
        treatment_group != canonical_treatment_group
        or include_eventpair != canonical_include_eventpair
    )


def get_panel_path(event_type: str, event_requirement: int, treatment_group: str) -> Path:
    req_folder = f"req{event_requirement}"
    if is_indirect_interlock(event_type):
        return (
            DATA_ROOT
            / "quarter-level"
            / f"{EVENT_CONFIGS[event_type]['panel_stem']}_{req_folder}.csv"
        )
    return (
        DATA_ROOT
        / f"quarter-level_{treatment_group}"
        / f"{EVENT_CONFIGS[event_type]['panel_stem']}_{req_folder}.csv"
    )


def get_level_folder(event_type: str, treatment_group: str, include_eventpair: int) -> str:
    if is_indirect_interlock(event_type):
        return "quarter-level"

    counterpart = "B" if treatment_group == "A" else "A"
    relation = "with" if include_eventpair == 1 else "without"
    return f"quarter-level_{treatment_group}_{relation}_{counterpart}"


class CohortPanelMaker:
    """Generate quarter-level event cohort CSV files."""

    def __init__(self, config: dict) -> None:
        self.config = config
        self.movement_candidates: pd.DataFrame | None = None
        self.movement_table: pd.DataFrame | None = None
        self.firm_interlock_panel: pd.DataFrame | None = None
        self.other_event_timing: dict[tuple[str, str, int], pd.DataFrame] = {}

    def run(self) -> None:
        event_types = self.config["event_types"]
        control_types = self.config["control_types"]
        treatment_groups = self.config["treatment_groups"]
        include_eventpair_values = self.config["include_eventpair"]
        event_requirements = self.config["event_requirements"]
        balanced_states = self.config["balanced_states"]
        canonical_treatment_group = treatment_groups[0]
        canonical_include_eventpair = include_eventpair_values[0]

        for treatment_group in treatment_groups:
            for include_eventpair in include_eventpair_values:
                for event_type in event_types:
                    if should_skip_repeated_nondirectional_run(
                        event_type=event_type,
                        treatment_group=treatment_group,
                        include_eventpair=include_eventpair,
                        canonical_treatment_group=canonical_treatment_group,
                        canonical_include_eventpair=canonical_include_eventpair,
                    ):
                        continue
                    for event_requirement in event_requirements:
                        for control_type in control_types:
                            for balanced in balanced_states:
                                direction_msg = (
                                    "treatment_group=ignored, include_eventpair=ignored"
                                    if is_indirect_interlock(event_type)
                                    else (
                                        f"treatment_group={treatment_group}, "
                                        f"include_eventpair={include_eventpair}"
                                    )
                                )
                                print(
                                    "Running cohort build: "
                                    f"quarter, {direction_msg}, "
                                    f"event_type={event_type}, req{event_requirement}, "
                                    f"control_type={control_type}, balanced={balanced}"
                                )
                                self.build_configuration(
                                    event_type=event_type,
                                    event_requirement=event_requirement,
                                    control_type=control_type,
                                    balanced=balanced,
                                    treatment_group=treatment_group,
                                    include_eventpair=include_eventpair,
                                )

    def build_configuration(
        self,
        event_type: str,
        event_requirement: int,
        control_type: str,
        balanced: int,
        treatment_group: str,
        include_eventpair: int,
    ) -> None:
        req_folder = f"req{event_requirement}"
        panel_path = get_panel_path(
            event_type=event_type,
            event_requirement=event_requirement,
            treatment_group=treatment_group,
        )

        df = pd.read_csv(panel_path)
        df["year"] = pd.to_numeric(df["year"], errors="raise").astype(int)
        df["quarter"] = pd.to_numeric(df["quarter"], errors="raise").astype(int)
        df["event"] = pd.to_numeric(df["event"], errors="raise").astype("int8")
        df["pure_event"] = pd.to_numeric(df["pure_event"], errors="raise").astype("int8")
        df["first_event_year"] = pd.to_numeric(df["first_event_year"], errors="coerce")

        level_folder = get_level_folder(
            event_type=event_type,
            treatment_group=treatment_group,
            include_eventpair=include_eventpair,
        )
        output_root = COHORT_DATA_ROOT / level_folder / "event" / req_folder

        start_year = int(self.config["plot_start_year"])
        end_year = int(self.config["plot_end_year"])

        for cohort_year in range(start_year, end_year + 1):
            event_col = f"event_{cohort_year}"
            balance_col = f"balance_panel_{cohort_year}"
            df[event_col] = pd.to_numeric(df[event_col], errors="raise").astype("int8")
            df[balance_col] = pd.to_numeric(df[balance_col], errors="raise").astype("int8")

            cohort_df = self.build_one_cohort(
                df=df,
                event_type=event_type,
                event_requirement=event_requirement,
                control_type=control_type,
                balanced=balanced,
                treatment_group=treatment_group,
                include_eventpair=include_eventpair,
                cohort_year=cohort_year,
            )

            output_dir = output_root / CONTROL_FOLDER_MAP[control_type]
            output_dir.mkdir(parents=True, exist_ok=True)
            balanced_suffix = "_balanced" if balanced == 1 else ""
            output_file = output_dir / f"{event_type}_quarter_cohort_{cohort_year}{balanced_suffix}.csv"
            cohort_df.to_csv(output_file, index=False)

        print(f"Finished. Files saved to: {output_root}")

    def build_one_cohort(
        self,
        df: pd.DataFrame,
        event_type: str,
        event_requirement: int,
        control_type: str,
        balanced: int,
        treatment_group: str,
        include_eventpair: int,
        cohort_year: int,
    ) -> pd.DataFrame:
        id_cols = ["BoardName", "product"]
        event_col = f"event_{cohort_year}"
        balance_col = f"balance_panel_{cohort_year}"
        start = cohort_year - int(self.config["window_pre"])
        end = cohort_year + int(self.config["window_post"])
        window_years = list(range(start, end + 1))
        expected_n = len(window_years) * 4
        df_window = df[df["year"].between(start, end)].copy()

        pure_event_at_t = (
            df.loc[df["year"].eq(cohort_year)]
            .groupby("BoardName")["pure_event"]
            .max()
        )
        treated_candidate_firms = set(pure_event_at_t[pure_event_at_t.eq(1)].index)
        control_candidate_firms = set(df["BoardName"].dropna().unique()) - treated_candidate_firms
        req_event_firms = set(df.loc[df[event_col].eq(1), "BoardName"].dropna().unique())
        final_treated_firms = treated_candidate_firms & req_event_firms

        treated = df_window[df_window["BoardName"].isin(final_treated_firms)].copy()
        if balanced == 1:
            treated_obs = treated.groupby(id_cols).size()
            complete_treated = treated_obs[treated_obs.eq(expected_n)].index
            treated = treated[
                treated.set_index(id_cols).index.isin(complete_treated)
                & treated[balance_col].eq(1)
            ].copy()

        no_pure_event = df_window.groupby(id_cols)["pure_event"].max()
        valid_control_units = no_pure_event[no_pure_event.eq(0)].index
        controls = df_window[
            df_window["BoardName"].isin(control_candidate_firms)
            & df_window.set_index(id_cols).index.isin(valid_control_units)
        ].copy()

        controls_obs = controls.groupby(id_cols).size()
        complete_controls = controls_obs[controls_obs.eq(expected_n)].index
        controls = controls[
            controls.set_index(id_cols).index.isin(complete_controls)
        ].copy()

        if control_type == "pure_control":
            controls = controls[controls["first_event_year"].isna()].copy()
        elif control_type == "not_yet":
            controls = controls[
                controls["first_event_year"].isna()
                | (controls["first_event_year"] > end)
            ].copy()

        if include_eventpair == 0 and not controls.empty and not is_indirect_interlock(event_type):
            controls = self.filter_counterpart_only_controls(
                controls=controls,
                event_type=event_type,
                event_requirement=event_requirement,
                treatment_group=treatment_group,
                cohort_year=cohort_year,
            )

        if not controls.empty and controls[event_col].ne(0).any():
            group_label = "non-directional" if is_indirect_interlock(event_type) else treatment_group
            raise AssertionError(
                f"Controls should have {event_col}=0 after pure_event filtering: "
                f"{event_type}, req{event_requirement}, {group_label}, {cohort_year}"
            )

        cohort_df = pd.concat([treated, controls], axis=0, ignore_index=True)
        cohort_df = cohort_df.sort_values(id_cols + ["year", "quarter"]).reset_index(drop=True)

        if event_requirement == 2 and not is_indirect_interlock(event_type):
            cohort_df = self.add_req2_control_variation(
                cohort_df=cohort_df,
                controls=controls,
                window_years=window_years,
            )

        if not is_indirect_interlock(event_type):
            cohort_df = self.add_other_event_markers(
                cohort_df=cohort_df,
                event_type=event_type,
                event_requirement=event_requirement,
                treatment_group=treatment_group,
            )
            cohort_df = self.add_ever_event_markers(
                cohort_df=cohort_df,
                cohort_year=cohort_year,
                event_requirement=event_requirement,
                treatment_group=treatment_group,
            )
        return cohort_df

    def filter_counterpart_only_controls(
        self,
        controls: pd.DataFrame,
        event_type: str,
        event_requirement: int,
        treatment_group: str,
        cohort_year: int,
    ) -> pd.DataFrame:
        if self.movement_candidates is None:
            self.movement_candidates = pd.read_csv(MOVEMENT_CANDIDATES_PATH)

        movement = self.movement_candidates.copy()
        stay_cols = [
            str(column)
            for column in movement.columns
            if re.fullmatch(r"stay_\d+_years", str(column))
        ]
        if len(stay_cols) != 1:
            raise ValueError(f"Expected exactly one stay_x_years column, found: {stay_cols}")

        stay_col = stay_cols[0]
        movement["event_year"] = pd.to_numeric(movement["event_year"], errors="raise").astype(int)
        for col in (stay_col, "requirement1", "requirement2_A", "requirement2_B"):
            movement[col] = pd.to_numeric(movement[col], errors="raise").astype("int8")

        current = movement.loc[
            movement["event_type"].eq(event_type)
            & movement["event_year"].eq(cohort_year)
            & movement[stay_col].eq(1)
        ].copy()
        if event_requirement in {1, 2}:
            current = current[current["requirement1"].eq(1)].copy()
        if event_requirement == 2:
            current = current[current[f"requirement2_{treatment_group}"].eq(1)].copy()

        firms_a = set(current["FirmA"].dropna())
        firms_b = set(current["FirmB"].dropna())
        drop_firms = firms_b - firms_a if treatment_group == "A" else firms_a - firms_b
        return controls[~controls["BoardName"].isin(drop_firms)].copy()

    def add_req2_control_variation(
        self,
        cohort_df: pd.DataFrame,
        controls: pd.DataFrame,
        window_years: list[int],
    ) -> pd.DataFrame:
        cohort_df = cohort_df.copy()
        marker_cols = [
            "control_stable",
            "control_changing",
            "control_stable_interlock",
            "control_stable_no_interlock",
        ]
        for col in marker_cols:
            cohort_df[col] = 0

        control_boards = set(controls["BoardName"].dropna().unique())
        if not control_boards:
            cohort_df[marker_cols] = cohort_df[marker_cols].astype("int8")
            return cohort_df

        if self.firm_interlock_panel is None:
            self.firm_interlock_panel = pd.read_csv(FIRM_INTERLOCK_PANEL_PATH)
            self.firm_interlock_panel["year"] = pd.to_numeric(
                self.firm_interlock_panel["year"],
                errors="raise",
            ).astype(int)

        current_interlocks = self.firm_interlock_panel.loc[
            self.firm_interlock_panel["BoardName"].isin(control_boards)
            & self.firm_interlock_panel["year"].isin(window_years)
        ].copy()
        interlock_lookup: dict[tuple[str, int], set[str]] = {}
        if not current_interlocks.empty:
            grouped = (
                current_interlocks.groupby(["BoardName", "year"])["CounterpartBoard"]
                .agg(lambda values: set(values.dropna().tolist()))
                .reset_index()
            )
            interlock_lookup = {
                (board_name, int(year)): counterpart_set
                for board_name, year, counterpart_set in grouped.itertuples(index=False, name=None)
            }

        for board_name in sorted(control_boards):
            counterpart_sets = [
                interlock_lookup.get((board_name, year), set())
                for year in window_years
            ]
            is_stable = all(
                current_set == previous_set
                for previous_set, current_set in zip(counterpart_sets, counterpart_sets[1:])
            )
            if not is_stable:
                classification = "changing"
            elif all(counterpart_sets):
                classification = "stable_interlock"
            else:
                classification = "stable_no_interlock"

            board_mask = cohort_df["BoardName"].eq(board_name)
            if classification in {"stable_interlock", "stable_no_interlock"}:
                cohort_df.loc[board_mask, "control_stable"] = 1
            cohort_df.loc[board_mask, f"control_{classification}"] = 1

        cohort_df[marker_cols] = cohort_df[marker_cols].astype("int8")
        return cohort_df

    def add_other_event_markers(
        self,
        cohort_df: pd.DataFrame,
        event_type: str,
        event_requirement: int,
        treatment_group: str,
    ) -> pd.DataFrame:
        if event_type == "to_B_not_in_A":
            other_events = [] if event_requirement == 2 else ["to_B_still_in_A", "interlock_dissolution"]
        elif event_type == "to_B_still_in_A":
            other_events = (
                ["to_B_not_in_A"]
                if event_requirement == 2
                else ["to_B_not_in_A", "interlock_dissolution"]
            )
        else:
            other_events = (
                ["to_B_not_in_A"]
                if event_requirement == 2
                else ["to_B_not_in_A", "to_B_still_in_A"]
            )

        cohort_df = cohort_df.copy()
        q1_mask = cohort_df["quarter"].eq(1)
        row_index = pd.MultiIndex.from_frame(cohort_df[["BoardName", "year"]])
        req_folder = f"req{event_requirement}"

        for other_event in other_events:
            cache_key = (other_event, treatment_group, event_requirement)
            if cache_key not in self.other_event_timing:
                panel_path = (
                    DATA_ROOT
                    / f"quarter-level_{treatment_group}"
                    / f"{EVENT_CONFIGS[other_event]['panel_stem']}_{req_folder}.csv"
                )
                timing = pd.read_csv(panel_path, usecols=["BoardName", "year", "event"])
                timing["year"] = pd.to_numeric(timing["year"], errors="raise").astype(int)
                timing["event"] = pd.to_numeric(timing["event"], errors="raise").astype("int8")
                self.other_event_timing[cache_key] = (
                    timing.loc[timing["event"].eq(1), ["BoardName", "year"]]
                    .drop_duplicates()
                    .reset_index(drop=True)
                )

            timing_index = pd.MultiIndex.from_frame(
                self.other_event_timing[cache_key][["BoardName", "year"]]
            )
            cohort_df[EVENT_CONFIGS[other_event]["other_col"]] = (
                q1_mask & row_index.isin(timing_index)
            ).astype("int8")

        return cohort_df

    def add_ever_event_markers(
        self,
        cohort_df: pd.DataFrame,
        cohort_year: int,
        event_requirement: int,
        treatment_group: str,
    ) -> pd.DataFrame:
        if self.movement_table is None:
            self.movement_table = pd.read_csv(MOVEMENT_TABLE_PATH)
            self.movement_table["year"] = pd.to_numeric(
                self.movement_table["year"],
                errors="raise",
            ).astype(int)
            self.movement_table["firm_type"] = self.movement_table["firm_type"].astype(str).str.upper()
            for req_col in ("req0", "req1", "req2"):
                self.movement_table[req_col] = pd.to_numeric(
                    self.movement_table[req_col],
                    errors="raise",
                ).astype("int8")

        req_col = f"req{event_requirement}"
        prior_events = self.movement_table.loc[
            self.movement_table["firm_type"].eq(treatment_group)
            & self.movement_table[req_col].eq(1)
            & self.movement_table["year"].lt(cohort_year)
        ]

        cohort_df = cohort_df.copy()
        for prior_event in MOVEMENT_EVENTS:
            firms = set(prior_events.loc[prior_events["event_type"].eq(prior_event), "BoardName"])
            cohort_df[EVENT_CONFIGS[prior_event]["ever_col"]] = (
                cohort_df["BoardName"].isin(firms).astype("int8")
            )
        return cohort_df

class CohortPlotter:
    """Plot treated/control cohort distributions from generated cohort CSV files."""

    def __init__(self, config: dict) -> None:
        self.config = config

    def run(self) -> None:
        event_types = self.config["event_types"]
        treat_types = self.config["treat_types"]
        control_types = self.config["control_types"]
        control_variations = self.config["control_variations"]
        treatment_groups = self.config["treatment_groups"]
        include_eventpair_values = self.config["include_eventpair"]
        event_requirements = self.config["event_requirements"]
        balanced_states = self.config["balanced_states"]
        canonical_treatment_group = treatment_groups[0]
        canonical_include_eventpair = include_eventpair_values[0]

        for treatment_group in treatment_groups:
            for include_eventpair in include_eventpair_values:
                for event_type in event_types:
                    if should_skip_repeated_nondirectional_run(
                        event_type=event_type,
                        treatment_group=treatment_group,
                        include_eventpair=include_eventpair,
                        canonical_treatment_group=canonical_treatment_group,
                        canonical_include_eventpair=canonical_include_eventpair,
                    ):
                        continue
                    for event_requirement in event_requirements:
                        for unit_level in DISTRIBUTION_CONFIGS:
                            self.plot_configuration(
                                event_type=event_type,
                                event_requirement=event_requirement,
                                treatment_group=treatment_group,
                                include_eventpair=include_eventpair,
                                unit_level=unit_level,
                                treat_types=treat_types,
                                control_types=control_types,
                                control_variations=control_variations,
                                balanced_states=balanced_states,
                            )

    def plot_configuration(
        self,
        event_type: str,
        event_requirement: int,
        treatment_group: str,
        include_eventpair: int,
        unit_level: str,
        treat_types: list[str],
        control_types: list[str],
        control_variations: list[str],
        balanced_states: list[int],
    ) -> None:
        unit_config = DISTRIBUTION_CONFIGS[unit_level]
        id_cols = unit_config["id_cols"]
        years = list(range(int(self.config["plot_start_year"]), int(self.config["plot_end_year"]) + 1))
        level_folder = get_level_folder(
            event_type=event_type,
            treatment_group=treatment_group,
            include_eventpair=include_eventpair,
        )
        req_folder = f"req{event_requirement}"

        for treat_type in treat_types:
            cohort_root = COHORT_DATA_ROOT / level_folder / treat_type / req_folder
            for control_type in control_types:
                folder_name = CONTROL_FOLDER_MAP[control_type]
                for balanced in balanced_states:
                    balanced_label = "balanced" if balanced == 1 else "unbalanced"
                    balanced_suffix = "_balanced" if balanced == 1 else ""
                    treated_counts: list[int] = []

                    if event_requirement == 2 and not is_indirect_interlock(event_type):
                        plot_segments = [
                            segment for segment in REQ2_STACK_SEGMENTS
                            if segment in control_variations
                        ]
                        segment_counts = {segment: [] for segment in plot_segments}
                        for year in years:
                            event_col = f"event_{year}"
                            file_path = (
                                cohort_root
                                / folder_name
                                / f"{event_type}_quarter_cohort_{year}{balanced_suffix}.csv"
                            )
                            if not file_path.exists():
                                treated_counts.append(0)
                                for segment in plot_segments:
                                    segment_counts[segment].append(0)
                                continue

                            df = pd.read_csv(file_path)
                            treated = df[df[event_col].eq(1)]
                            controls = df[df[event_col].eq(0)]
                            treated_counts.append(treated[id_cols].drop_duplicates().shape[0])

                            for segment in plot_segments:
                                segment_col = f"control_{segment}"
                                segment_counts[segment].append(
                                    controls[controls[segment_col].eq(1)][id_cols]
                                    .drop_duplicates()
                                    .shape[0]
                                )

                        self.draw_stacked_req2_plot(
                            years=years,
                            treated_counts=treated_counts,
                            segment_counts=segment_counts,
                            plot_segments=plot_segments,
                            unit_config=unit_config,
                            title=(
                                f"{level_folder} | {unit_config['title_label']} | "
                                f"{event_type} | {treat_type} | req{event_requirement} | "
                                f"{control_type} | {balanced_label}"
                            ),
                            out_path=(
                                PROJECT_ROOT
                                / "figures"
                                / unit_config["figure_root"]
                                / level_folder
                                / treat_type
                                / req_folder
                                / folder_name
                                / f"{event_type}_{level_folder}_{treat_type}_{control_type}_{balanced_label}.png"
                            ),
                        )
                        csv_dir = (
                            PROJECT_ROOT
                            / "csv"
                            / unit_config["figure_root"]
                            / level_folder
                            / treat_type
                            / req_folder
                            / folder_name
                        )
                        csv_dir.mkdir(parents=True, exist_ok=True)
                        csv_data = {"Year": years, "Treated": treated_counts}
                        for segment in plot_segments:
                            csv_data[f"Control: {segment}"] = segment_counts[segment]
                        pd.DataFrame(csv_data).to_csv(
                            csv_dir / f"{event_type}_{level_folder}_{treat_type}_{control_type}_{balanced_label}.csv",
                            index=False,
                        )
                    else:
                        control_counts: list[int] = []
                        for year in years:
                            event_col = f"event_{year}"
                            file_path = (
                                cohort_root
                                / folder_name
                                / f"{event_type}_quarter_cohort_{year}{balanced_suffix}.csv"
                            )
                            if not file_path.exists():
                                treated_counts.append(0)
                                control_counts.append(0)
                                continue

                            df = pd.read_csv(file_path)
                            treated = df[df[event_col].eq(1)]
                            controls = df[df[event_col].eq(0)]
                            treated_counts.append(treated[id_cols].drop_duplicates().shape[0])
                            control_counts.append(controls[id_cols].drop_duplicates().shape[0])

                        self.draw_two_bar_plot(
                            years=years,
                            treated_counts=treated_counts,
                            control_counts=control_counts,
                            unit_config=unit_config,
                            title=(
                                f"{level_folder} | {unit_config['title_label']} | "
                                f"{event_type} | {treat_type} | req{event_requirement} | "
                                f"{control_type} | {balanced_label}"
                            ),
                            out_path=(
                                PROJECT_ROOT
                                / "figures"
                                / unit_config["figure_root"]
                                / level_folder
                                / treat_type
                                / req_folder
                                / folder_name
                                / f"{event_type}_{level_folder}_{treat_type}_{control_type}_{balanced_label}.png"
                            ),
                        )
                        csv_dir = (
                            PROJECT_ROOT
                            / "csv"
                            / unit_config["figure_root"]
                            / level_folder
                            / treat_type
                            / req_folder
                            / folder_name
                        )
                        csv_dir.mkdir(parents=True, exist_ok=True)
                        pd.DataFrame(
                            {"Year": years, "Treated": treated_counts, "Control": control_counts}
                        ).to_csv(
                            csv_dir / f"{event_type}_{level_folder}_{treat_type}_{control_type}_{balanced_label}.csv",
                            index=False,
                        )

        print(
            "Figures and CSV tables generated and saved to:\n"
            f"  {PROJECT_ROOT}/figures/{unit_config['figure_root']}/\n"
            f"  {PROJECT_ROOT}/csv/{unit_config['figure_root']}/"
        )

    def draw_stacked_req2_plot(
        self,
        years: list[int],
        treated_counts: list[int],
        segment_counts: dict[str, list[int]],
        plot_segments: list[str],
        unit_config: dict,
        title: str,
        out_path: Path,
    ) -> None:
        x = list(range(len(years)))
        width = 0.35
        plt.figure(figsize=(14, 6))

        bars_treated = plt.bar(
            [index - width / 2 for index in x],
            treated_counts,
            width=width,
            label="Treated",
        )
        control_bottom = [0] * len(years)
        for segment in plot_segments:
            values = segment_counts[segment]
            plt.bar(
                [index + width / 2 for index in x],
                values,
                width=width,
                bottom=control_bottom,
                label=f"Control: {segment}",
                color=REQ2_STACK_COLORS[segment],
            )
            control_bottom = [bottom + value for bottom, value in zip(control_bottom, values)]

        self.finish_plot(
            years=years,
            bars_to_label=[bars_treated],
            extra_totals=control_bottom,
            unit_config=unit_config,
            title=title,
            out_path=out_path,
        )

    def draw_two_bar_plot(
        self,
        years: list[int],
        treated_counts: list[int],
        control_counts: list[int],
        unit_config: dict,
        title: str,
        out_path: Path,
    ) -> None:
        x = list(range(len(years)))
        width = 0.35
        plt.figure(figsize=(14, 6))
        bars_treated = plt.bar(
            [index - width / 2 for index in x],
            treated_counts,
            width=width,
            label="Treated",
        )
        bars_control = plt.bar(
            [index + width / 2 for index in x],
            control_counts,
            width=width,
            label="Control",
        )
        self.finish_plot(
            years=years,
            bars_to_label=[bars_treated, bars_control],
            extra_totals=None,
            unit_config=unit_config,
            title=title,
            out_path=out_path,
        )

    def finish_plot(
        self,
        years: list[int],
        bars_to_label: list,
        extra_totals: list[int] | None,
        unit_config: dict,
        title: str,
        out_path: Path,
    ) -> None:
        for bars in bars_to_label:
            for bar in bars:
                height = bar.get_height()
                plt.text(
                    bar.get_x() + bar.get_width() / 2,
                    height + 1,
                    f"{int(height)}",
                    ha="center",
                    va="bottom",
                    fontsize=10,
                )

        if extra_totals is not None:
            x = list(range(len(years)))
            for xpos, total in zip([index + 0.35 / 2 for index in x], extra_totals):
                plt.text(
                    xpos,
                    total + 1,
                    f"{int(total)}",
                    ha="center",
                    va="bottom",
                    fontsize=10,
                )

        plt.xticks(list(range(len(years))), years, rotation=45)
        plt.ylabel(unit_config["ylabel"])
        plt.title(title)
        plt.legend()
        plt.tight_layout()
        out_path.parent.mkdir(parents=True, exist_ok=True)
        plt.savefig(out_path)
        plt.close()


if __name__ == "__main__":
    CohortPanelMaker(RUN_CONFIG).run()
    CohortPlotter(RUN_CONFIG).run()
